# Generated by Django 3.2 on 2021-12-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=4, unique=True, verbose_name='官署コード')),
                ('name', models.CharField(max_length=32, verbose_name='官署名')),
                ('shortcut_name', models.CharField(max_length=8, verbose_name='官署略称')),
            ],
            options={
                'db_table': 'offices',
            },
        ),
    ]
