# Generated by Django 3.2 on 2021-12-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='update_at',
            field=models.DateTimeField(default='2001-01-01 00:00', verbose_name='更新日時'),
            preserve_default=False,
        ),
    ]
