# Generated by Django 3.2 on 2022-01-07 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_office_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='slug',
        ),
        migrations.AlterField(
            model_name='office',
            name='id',
            field=models.SlugField(editable=False, max_length=4, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[0-9A-Z]*$', 'Only A-Z and 0-9 chatacters are allowed')], verbose_name='官署コード'),
        ),
    ]
