# Generated by Django 3.2 on 2022-01-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_auto_20220107_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='unyo_sts',
            field=models.BooleanField(default=True, verbose_name='運用状態'),
            preserve_default=False,
        ),
    ]
