# Generated by Django 3.2 on 2022-04-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0004_office_unyo_sts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='unyo_sts',
            field=models.BooleanField(default=True, verbose_name='運用状態'),
        ),
    ]
