# Generated by Django 3.2 on 2022-01-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EqType',
            fields=[
                ('id', models.CharField(editable=False, max_length=24, primary_key=True, serialize=False, verbose_name='装置型式')),
                ('create_at', models.DateTimeField(verbose_name='登録日時')),
            ],
            options={
                'db_table': 'eqtypes',
            },
        ),
    ]
