# Generated by Django 3.2 on 2022-01-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eqtype',
            name='slug',
            field=models.SlugField(default='Asia/Tokyo', editable=False, max_length=24, unique=True, verbose_name='装置型式(URL)'),
            preserve_default=False,
        ),
    ]
