# Generated by Django 3.2 on 2022-05-01 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='menus',
        ),
    ]
