# Generated by Django 3.2 on 2022-05-01 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_attachmentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='content',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='contents.contents', verbose_name='コンテンツ'),
            preserve_default=False,
        ),
    ]
