# Generated by Django 3.2 on 2022-05-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_menu_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='content',
        ),
    ]
