# Generated by Django 3.2 on 2022-05-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_menu_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='sort_num',
            field=models.IntegerField(verbose_name='並び順'),
        ),
    ]
