# Generated by Django 3.2 on 2021-12-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name='対象データ')),
                ('update_at', models.DateTimeField(verbose_name='更新日時')),
            ],
            options={
                'db_table': 'histories',
            },
        ),
    ]
