# Generated by Django 3.2 on 2021-12-23 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0002_rename_office_history'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='HistoryDB',
        ),
    ]
