# Generated by Django 3.2 on 2021-12-17 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='content',
        ),
    ]
