# Generated by Django 3.2 on 2021-12-17 07:05

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0002_remove_info_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='content',
            field=mdeditor.fields.MDTextField(blank=True, default='', verbose_name='内容'),
        ),
    ]
