# Generated by Django 3.2 on 2021-12-18 10:07

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0003_info_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='detail',
            field=markdownx.models.MarkdownxField(blank=True, default='', verbose_name='詳細'),
        ),
    ]
