# Generated by Django 3.2 on 2021-12-18 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0004_info_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='detail',
        ),
    ]
