# Generated by Django 3.2 on 2021-12-19 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infos', '0005_remove_info_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='登録者'),
            preserve_default=False,
        ),
    ]
