# Generated by Django 3.2 on 2021-12-25 06:00

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infos', '0007_alter_info_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='infos_info_create', to=settings.AUTH_USER_MODEL, verbose_name='登録者'),
        ),
        migrations.AlterField(
            model_name='info',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='infos_info_update', to=settings.AUTH_USER_MODEL, verbose_name='更新者'),
        ),
    ]
