# Generated by Django 3.2 on 2021-12-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0008_auto_20211225_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='内容'),
        ),
    ]
