# Generated by Django 3.2 on 2021-12-30 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0012_rename_isrichtext_info_is_rich_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default='', max_length=64, upload_to='', verbose_name='ファイル名')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infos.info')),
            ],
            options={
                'db_table': 'info_attachments',
            },
        ),
    ]
