# Generated by Django 3.2 on 2022-01-01 03:05

from django.db import migrations, models
import infos.models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0013_infoattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoattachment',
            name='file',
        ),
        migrations.AddField(
            model_name='infoattachment',
            name='attachment',
            field=models.FileField(blank=True, default='', max_length=64, upload_to=infos.models.file_upload_path, verbose_name='ファイル名'),
        ),
    ]
