# Generated by Django 3.2 on 2022-01-01 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0014_auto_20220101_1205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoAttachment',
        ),
    ]
