# Generated by Django 3.2 on 2022-01-01 06:18

from django.db import migrations, models
import infos.models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0016_infoattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoattachment',
            name='attachment',
            field=models.FileField(blank=True, default='', max_length=64, null=True, upload_to=infos.models.file_upload_path, verbose_name='ファイル名'),
        ),
    ]
