# Generated by Django 3.2 on 2022-01-01 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0018_alter_infoattachment_attachment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfoAttachment',
            new_name='InfoAttachmentFile',
        ),
    ]
