# Generated by Django 3.2 on 2022-01-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0019_rename_infoattachment_infoattachmentfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfoAttachmentFile',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='attachment',
            new_name='file',
        ),
    ]
