# Generated by Django 3.2 on 2022-01-02 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0021_rename_file_attachment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attachment',
            new_name='InfoFile',
        ),
    ]
