# Generated by Django 3.2 on 2022-01-02 09:41

from django.db import migrations, models
import rise_info.baseModels


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0022_rename_attachment_infofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='infofile',
            name='filename',
            field=models.CharField(default='', max_length=64, verbose_name='ファイル名'),
        ),
        migrations.AlterField(
            model_name='infofile',
            name='file',
            field=models.FileField(upload_to=rise_info.baseModels.file_upload_path, verbose_name='ファイル'),
        ),
    ]
