# Generated by Django 3.2 on 2022-01-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0024_auto_20220103_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='info_type',
            field=models.CharField(choices=[('technical', '信頼性技術情報'), ('failure_case', '障害事例情報'), ('safety', '安全情報'), ('event', 'イベント情報')], default='technical', max_length=16, verbose_name='情報種別'),
        ),
        migrations.AddField(
            model_name='info',
            name='managerID',
            field=models.CharField(default='TMC-解析-', max_length=32, verbose_name='管理番号'),
        ),
    ]
