# Generated by Django 3.2 on 2021-12-25 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FailuerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128, verbose_name='タイトル')),
                ('sammary', models.TextField(blank=True, default='', max_length=512, verbose_name='概要')),
                ('content', mdeditor.fields.MDTextField(blank=True, default='', verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='failuer_reports_failuerreport_create', to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='failuer_reports_failuerreport_update', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'db_table': 'failuer_reports',
            },
        ),
    ]
