# Generated by Django 3.2 on 2021-12-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failuer_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='failuerreport',
            name='flight_impact',
            field=models.TextField(blank=True, default='', max_length=128, verbose_name='運航への影響'),
        ),
        migrations.AddField(
            model_name='failuerreport',
            name='is_flight_impact',
            field=models.BooleanField(default=False, verbose_name='運航への影響有無'),
        ),
        migrations.AddField(
            model_name='failuerreport',
            name='is_operatinal_impact',
            field=models.BooleanField(default=False, verbose_name='運用への影響有無'),
        ),
        migrations.AddField(
            model_name='failuerreport',
            name='operatinal_impact',
            field=models.TextField(blank=True, default='', max_length=128, verbose_name='運用への影響'),
        ),
    ]
