# Generated by Django 3.2 on 2021-12-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failuer_reports', '0002_auto_20211226_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failuerreport',
            name='flight_impact',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='運航への影響'),
        ),
        migrations.AlterField(
            model_name='failuerreport',
            name='operatinal_impact',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='運用への影響'),
        ),
    ]
