# Generated by Django 3.2 on 2021-12-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failuer_reports', '0003_auto_20211226_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failuerreport',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='内容'),
        ),
    ]
