# Generated by Django 3.2 on 2022-01-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('failuer_reports', '0013_auto_20220103_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failuerreport',
            name='is_rich_text',
        ),
    ]
