# Generated by Django 3.2 on 2022-01-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('failuer_reports', '0015_circumstances'),
    ]

    operations = [
        migrations.AddField(
            model_name='circumstances',
            name='event',
            field=models.TextField(default='Asia/Tokyo', max_length=256, verbose_name='事案'),
            preserve_default=False,
        ),
    ]
