# Generated by Django 3.2 on 2022-01-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('failuer_reports', '0016_circumstances_event'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='circumstances',
            table='circumstance',
        ),
    ]
