# Generated by Django 3.2 on 2022-01-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('failuer_reports', '0017_alter_circumstances_table'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='circumstances',
            managers=[
            ],
        ),
    ]
